# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7489ef6af71702830e4bb0ec7433bd31171dd026afbb3b01e4b886f83c4f365bf4ce84d6f5fc8eb87922f3955e668aa5f72405445ea997ec3f860c15433cb758

test:
  secret_key_base: 8ac86ab48d40cbbf0f6f9494ebc6df2d1312ca9dbd5f595c419446742df3c468885c723b8148c08908fff75cf62255ab326146d289d92cde9b709c21ab4b967e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
